#!/usr/bin/env bash
#creats file containging pid
tmp=/var/run/holbertonscript.pid
echo $$ > $tmp
trap 'echo I hate the kill command ; sudo rm '"tmp"'; exit' SIGTERM
trap "echo Y U no love me?!" SIGINT
trap 'sudo rm -f '"tmp"' ; exit' SIGQUIT
while :
do
    echo "To infinity and beyond"
    sleep 2
done
