#!/usr/bin/env bash
#creats file containging pid
touch /var/run/holbertonscript.pid
echo "$!" > /var/run/holbertonscript.pid
trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm /var/run/holbertonscript.pid" SIGQUIT
trap "rm /var/run/holbertonscript.pid" SIGTERM
while :
do
    echo "To infinity and beyond"
    sleep 2
done
