#!/usr/bin/env bash
# Fizz Buzz in Bash
x=1
for x in {1..100}
do
	if [ $((x % 15)) == "0" ]
	then
		echo "FizzBuzz"
	elif [ $((x % 5)) == "0" ]
	then
		echo "Buzz"
	elif [ $((x % 3)) == "0" ]
	then
		echo "Fizz"
	else
		echo "$x"
	fi
done
