#!/usr/bin/env bash
#displays "Holberton School" 10 times and "Hi"
x=1
while [ $x -le 10 ]
do
	echo "Holberton School"
	x=$((x + 1))
	if  [[ "$x" == '10' ]]; then
	    echo "Hi"
	fi
	   continue
done
