#!/usr/bin/env bash
# Displays number 1 - 20 with variations for 4th, 9th, and 17th iterations
x=0
while [ $x -le 20 ]
do
        echo "$x"
        x=$((x + 1))
	if [[ "$x" == '5' ]];
	then
		echo "bad luck from China"
	elif [[ "$x" == '10' ]];
	then
		echo "bad luck from Japan"
	elif [[ "$x" == '18' ]];
	then
		echo "bad luck from Italy"
	fi
		continue
done
